import type { prettierData } from '@liangskyli/utils';
import type { PathItemObject } from 'openapi-typescript';
import type { Definition } from 'typescript-json-schema';

export const fileTip =
  '// This file is auto generated by @liangskyli/openapi-gen-ts, do not edit!';

export const packageName = '@liangskyli/openapi-gen-ts';

export type IPrettierOptions = Parameters<typeof prettierData>[1];
export type OpenapiMethod = keyof Omit<
  PathItemObject,
  'servers' | 'parameters'
>;
export const methodList: OpenapiMethod[] = [
  'get',
  'put',
  'post',
  'delete',
  'options',
  'head',
  'patch',
  'trace',
];
export type OpenapiDefinition = Omit<Definition, 'properties'> & {
  properties?: { [key: string]: OpenapiDefinition };
};
