import type { prettierData } from '@liangskyli/utils';

export const fileTip =
  '// This file is auto generated by @liangskyli/openapi-gen-ts, do not edit!';

export const packageName = '@liangskyli/openapi-gen-ts';

export type IPrettierOptions = Parameters<typeof prettierData>[1];
